### ISSUE TITLE
PROMIS response options

### ISSUE THREAD

**Issue by akeshavan** [ReproNim/schema-standardization#139]
For questions on PROMIS like "What is the total number of general doctor visits you made in the last 12 months?" there is no option for 0! Shouldn't there be?

**Comment by sanuann** [comment]
check the questions in this document listed on page 3: https://docs.google.com/document/d/1Nv-zhYVi3JQdb4ZJGiBAAAYoQf2H6vnxdreS14qIBf0/edit
should ask abhi.
