### ISSUE TITLE
schema for a checklist for neurovault metadata

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/schema-standardization#236]
Hello,

I finally took the time to write a [script](https://github.com/Remi-Gau/COBIDAS_chckls/tree/master/python/create_neurovault_schema.py) to turn the neurovault [list of required inputs](https://github.com/Remi-Gau/COBIDAS_chckls/tree/master/xlsx/metadata_neurovault.csv) into a schema that can then be render with the schema-ui.

Are you interested in adding it in the tool folder?

Other related questions that appeared on this journey:

Also I think I read somewhere that you can "test" a schema? Is that possible? Because that would really help.
And I will definitely need to do more homework on the schemas in general: right now I am doing things but it is a very hit and miss. So any pointers to any documentation would help. :-)

**Comment by sanuann** [comment]
@Remi-Gau sure can add your scripts to our tools. FYI: I have moved tools to a different repository linked [here](https://github.com/ReproNim/reproschema-builder). Please send a PR to the repo.

**Comment by Remi-Gau** [comment]
I sent the PR.

That visualization really helps for sure! Thx
